Lab11-Dotnet/Library/Library/Controllers/LibrarianController.cs
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Linq;

namespace Library.Controllers
{
    [Authorize(Policy = "RequireEmail")]
    [Authorize(Roles = "Administrator")]
    public class LibrarianController : Controller
    {
        private LibraryContext _context;

        public LibrarianController(LibraryContext libraryContext)
        {
            _context = libraryContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddBook()
        {
            PopulateGenerDropDownList();
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("AddBook")]
        public IActionResult AddBookPost(Book book)
        {
            if (ModelState.IsValid)
            {
                if (book.PhotoAvatar != null && book.PhotoAvatar.Length > 0)
                {
                    book.ImageMimeType = book.PhotoAvatar.ContentType;
                    book.ImageName = Path.GetFileName(book.PhotoAvatar.FileName);
                    using (var memoryStream = new MemoryStream())
                    {
                        book.PhotoAvatar.CopyTo(memoryStream);
                        book.PhotoFile = memoryStream.ToArray();
                    }
                    book.Available = true;
                    _context.Add(book);
                    _context.SaveChanges();
                }
                return RedirectToAction(nameof(ThankYou));
            }
            PopulateGenerDropDownList(book.Genre.Id);
            return View();
        }

        public IActionResult ThankYou()
        {
            return View();
        }

        private void PopulateGenerDropDownList(int? selectedGener = null)
        {
            var genres = from b in _context.Genres
                         orderby b.Name
                         select b;

            ViewBag.GenerList = new SelectList(genres.AsNoTracking(), "Id", "Name", selectedGener);
        }
    }
}

Lab11-Dotnet/Library/Library/Controllers/LibraryController.cs
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class LibraryController : Controller
    {
        private LibraryContext _context;
        private IHostingEnvironment _environment;

        public LibraryController(LibraryContext libraryContext, IHostingEnvironment environment)
        {
            _context = libraryContext;
            _environment = environment;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var booksQuery = from b in _context.Books
                             where b.Recommended == true
                             orderby b.Author
                             select b;

            return View(booksQuery);
        }

        [Authorize]
        public IActionResult GetBooksByGener()
        {
            var booksGenerQuery = _context.Books.OrderBy(b => b.Genre.Name);
            return View(booksGenerQuery);
        }

        [Authorize]
        public IActionResult LendingBook(int id)
        {
            Book book = _context.Books.FirstOrDefault(b => b.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("LendingBook")]
        public async Task<IActionResult> LendingBookPost(int id)
        {
            var bookToUpdate = _context.Books.FirstOrDefault(b => b.Id == id);
            bookToUpdate.Available = false;
            if (await TryUpdateModelAsync<Book>(
                bookToUpdate,
                "",
                b => b.Available))
            {
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(bookToUpdate);
        }

        public IActionResult GetImage(int id)
        {
            Book requestedBook = _context.Books.FirstOrDefault(b => b.Id == id);
            if (requestedBook != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedBook.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedBook.ImageMimeType);
                }
                else
                {
                    if (requestedBook.PhotoFile.Length > 0)
                    {
                        return File(requestedBook.PhotoFile, requestedBook.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Lab11-Dotnet/Library/Library/Views/Librarian/AddBook.cshtml
@model Library.Models.Book

@{
    ViewData["Title"] = "AddBook";
}

<h1 class="title">Add Book to Library</h1>
<div class="row justify-content-center">
    <div class="col-4">
        <form class="submit-form" method="post" enctype="multipart/form-data" asp-action="AddBook">
            <div class="form-group row">
                <label asp-for="Genre" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <select asp-for="GenreId" asp-items="ViewBag.GenerList" type="text" class="form-control" placeholder="Geners" required></select>
                    <span asp-validation-for="GenreId"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Name" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="Name" type="text" class="form-control" placeholder="Name" required>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Author" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="Author" type="text" class="form-control" placeholder="Author" required>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="DatePublished" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="DatePublished" type="date" class="form-control" placeholder="Published Date" required>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="PhotoAvatar" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-6">
                    <input asp-for="PhotoAvatar" type="file" class="form-control" placeholder="Photo" required>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button id="formButton" type="submit" class="btn btn-outline-primary">
                        Add a Book
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}

Lab11-Dotnet/Library/Library/Views/Librarian/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1 class="title">Welcome to Workers Portal</h1>
<div class="text-center">
    <button class="btn btn-info" type="button" onclick="location.href='@Url.Action("AddBook", "Librarian")'">Add Book to the Library</button>
</div>

Lab11-Dotnet/Library/Library/Views/Librarian/ThankYou.cshtml
@{
    ViewData["Title"] = "ThankYou";
}

<h1 class="title">Thank You For Adding a Book to the Inventory</h1>

<div class="text-center">
    <button class="btn btn-info" type="button" onclick="location.href='@Url.Action("AddBook", "Librarian")'">Add Book to the Library</button>
    <button class="btn btn-info" type="button" onclick="location.href='@Url.Action("GetBooksByGener", "Library")'">Back to Our Books</button>
</div>